#############################  J1     J2    J3     J4      J5    J6      J7     H     LF     RF  ########################
th_min_self_avoidance:  #    [0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000]
  - 0.000
  - 0.000
  - 0.000
  - 0.000
  - 0.000
  - 0.000
  - 0.000
  - 0.000
  - 0.000
  - 0.000
th_max_self_avoidance:   #   [0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000]
  - 0.000
  - 0.000
  - 0.000
  - 0.000
  - 0.000
  - 0.000
  - 0.000
  - 0.000
  - 0.000
  - 0.000
##OBSTACLE
th_min_obstacle_avoidance:  #   [0.000, 0.010, 0.010, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000]
  - 0.000
  - 0.010
  - 0.010
  - 0.000
  - 0.000
  - 0.000
  - 0.000
  - 0.000
  - 0.000
  - 0.000 
th_max_obstacle_avoidance:  #   [0.000, 0.020, 0.020, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000]
  - 0.000
  - 0.020
  - 0.020
  - 0.000
  - 0.000
  - 0.000
  - 0.000     
  - 0.000
  - 0.000
  - 0.000   
##BIMANUAL
th_min_other_avoidance:    # [0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.030, 0.000, 0.000]
  - 0.000
  - 0.000
  - 0.000
  - 0.000
  - 0.000
  - 0.000
  - 0.000
  - 0.030
  - 0.000
  - 0.000
th_max_other_avoidance:     #[0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.050, 0.030, 0.030]
  - 0.000
  - 0.000
  - 0.000
  - 0.000
  - 0.000
  - 0.000
  - 0.000
  - 0.050
  - 0.030
  - 0.030
gain_teleop: 0.8
gain_obstacle_avoidance: 0.9
gain_self_avoidance: 0.9
gain_other_avoidance: 0.8
saturation_velocity: 0.8