#############################  J1     J2    J3     J4      J5    J6      J7     H     LF     RF  ########################
th_min_self_avoidance:  #    [0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000]
  - 0.000   # J1
  - 0.000   # J2
  - 0.000   # J3
  - 0.000   # J4
  - 0.000  # J5
  - 0.000  # J6
  - 0.000 # J7
  - 0.000 # H
  - 0.000 # LF
  - 0.000 # RF
th_max_self_avoidance:   #   [0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000]
  - 0.000  # J1
  - 0.000 # J2
  - 0.000   # J3
  - 0.000  # J4
  - 0.000   # J5
  - 0.000  # J6
  - 0.000 # J7
  - 0.000 # H
  - 0.000 # LF
  - 0.000 # RF
##OBSTACLE
th_min_obstacle_avoidance:  #   [0.000, 0.010, 0.010, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000]
  - 0.000 # J1
  - 0.005 # J2
  - 0.005 # J3
  - 0.000 # J4
  - 0.000 # J5
  - 0.000 # J6
  - 0.000 # J7
  - 0.000 # H
  - 0.000 # LF
  - 0.000   # RF
th_max_obstacle_avoidance:  #   [0.000, 0.020, 0.020, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000]
  - 0.000 # J1
  - 0.010 # J2
  - 0.015 # J3
  - 0.000 # J4
  - 0.000 # J5
  - 0.000 # J6
  - 0.000   # J7    
  - 0.000 # H
  - 0.000 # LF
  - 0.000   # RF 
##BIMANUAL
th_min_other_avoidance:    # [0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.030, 0.000, 0.000]
  - 0.000 # J1
  - 0.000 # J2
  - 0.000 # J3
  - 0.000 # J4
  - 0.000 # J5
  - 0.000 # J6
  - 0.000 # J7
  - 0.000 # H
  - 0.000 # LF
  - 0.000 # RF
th_max_other_avoidance:     #[0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.050, 0.030, 0.030]
  - 0.050 # J1
  - 0.050 # J2
  - 0.050 # J3
  - 0.050 # J4
  - 0.050 # J5
  - 0.050 # J6
  - 0.050 # J7
  - 0.050 # H
  - 0.030 # LF
  - 0.030 # RF
gain_teleop: 0.8
gain_obstacle_avoidance: 0.9
gain_self_avoidance: 0.9
gain_other_avoidance: 0.8
saturation_velocity: 0.8